/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HttpResponsePayload = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
});

export const idlService = IDL.Service({
  'fetchStockData' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'transformResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : HttpResponsePayload,
        }),
      ],
      [HttpResponsePayload],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HttpResponsePayload = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
  });
  
  return IDL.Service({
    'fetchStockData' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'transformResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : HttpResponsePayload,
          }),
        ],
        [HttpResponsePayload],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };